### ISSUE TITLE
A fix to BlInfiniteDataSource>>notifyWithEvent:

### ISSUE THREAD

**Issue by tinchodias** [feenkcom/bloc-pac#1]
Hello, I've found this code because I in pharo-graphics/Bloc we removed BlUniverse, then it's an undeclared variable here. I'd appreciate some feedback on how to correctly fix it. Or, what's the problem.

```smalltalk
BlInfiniteDataSource >>
notifyWithEvent: anEvent
	"Fire a given event ensuring that it will happen in UI Thread"

	self flag: 'Find a solution'.

	BlUniverse default isUIProcess
		ifTrue: [ self dispatchEvent: anEvent ]
		ifFalse: [ self dispatchEvent: anEvent ]
```

**Comment by syrel** [comment]
Hi @tinchodias 
Thank you for the issue. Over the years we learned that the best approach is to make users responsible for managing multiple processes explicitly, instead of magically handling them deep inside of the widgets.
It is rare when users even have to #notifyWithEvent: in the `BlInfiniteDataSource`.

Fixed.

**Comment by tinchodias** [comment]
thanks
